title: Iggo Nzioki Kanui Data Analytics Portfolio
logo: https://github.com/IggoNz/IggoNKanui.github.io/blob/Master/download.jpeg
description: Data analyst and data science enthusiast with three years of experience solving real-world problems through data-driven insights. Skilled in R, SQL, Excel, Power BI, and data visualization tools, with a track record of cleaning, analyzing, and synthesizing complex datasets. Experienced in creating interactive dashboards, reproducible code, and visual storytelling, with a focus on translating data into clear, actionable outcomes
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
